__TestingRidgeRegression and LogisticRegression__

__RidgeRegression:__
__1.__ Use the dataset cpu.csv;
__2.__ Divide the dataset into train and test sets;
__3.__ Train the model. Which score do you get? And the cost?

In [10]:
import numpy as np
import pandas as pd
from si.Data.dataset import Dataset
from si.IO.CSV import read_csv
from si.models.ridge_regression import RidgeRegression
from si.models.logistic_regression import LogisticRegression
from si.model_selection.split import train_test_split

In [3]:
cpu = read_csv(r'C:\Users\bruna\PycharmProjects\SIB\datasets\cpu\cpu.csv', sep=",", label=True, features=True)

In [13]:
# standardize data
from sklearn.preprocessing import StandardScaler
cpu.X = StandardScaler().fit_transform(cpu.X)
cpu.X

array([[-0.30358614, -0.67502598, -0.49546221,  5.69420785,  1.66198873,
         4.23103334],
       [-0.67332952,  1.32629082,  1.72704937,  0.16762947,  0.48550899,
         0.52947875],
       [-0.67332952,  1.32629082,  1.72704937,  0.16762947,  0.48550899,
         0.52947875],
       ...,
       [-0.30358614, -0.2243162 , -0.32449978, -0.62188173, -0.39685082,
        -0.16456273],
       [ 1.06369405, -0.60886675, -0.32449978,  0.16762947, -0.69097076,
        -0.70437278],
       [ 1.06369405, -0.48275071, -0.66642464, -0.62188173, -0.69097076,
        -0.70437278]])

In [15]:
# split dataset
train_dataset, test_dataset = train_test_split(cpu)
test_dataset.y

array([ 274,   30,   22,  915,   16,  326,   72,    6, 1144,  208,   65,
        130,   52,   45,   35,   36,   51,   31,  100,  132,   50,   60,
        110,   18,   11,   50,   69,   27,   19,   41,  248,   32,   45,
         26,   16,   26,   67,  465,   38,   17,  307], dtype=int64)

In [16]:
# ridge regressor
ridge = RidgeRegression(max_iter=2000)
ridge.fit(train_dataset)
predictions = ridge.predict(test_dataset)
predictions

array([85.94611784, 85.35015745, 85.3694493 , 87.42684616, 85.27879583,
       86.31493281, 85.49471799, 85.30536182, 88.25566648, 86.45770529,
       85.74249018, 85.78510864, 85.50054263, 85.51810529, 85.63519049,
       85.46966712, 85.95708075, 85.44403354, 85.99208375, 85.74045067,
       85.59587291, 85.4952241 , 85.87265818, 85.24205351, 85.17784684,
       85.4693721 , 85.29530217, 85.44891248, 85.42319969, 85.59596927,
       86.35132957, 85.50873762, 85.4179295 , 85.36893854, 85.24283118,
       85.49808416, 85.38574388, 86.72833292, 85.92461831, 85.38038651,
       87.22998553])

In [17]:
ridge.score(test_dataset)

53832.71450396599

In [18]:
ridge.cost(test_dataset)

26916.357986813502

In [19]:
ridge.cost_history

{0: 14415.970359769084,
 1: 14401.833258729703,
 2: 14391.126782757061,
 3: 14381.167802440186,
 4: 14371.388767520131,
 5: 14361.666728392947,
 6: 14351.973019139694,
 7: 14342.300846825365,
 8: 14332.64854074093,
 9: 14323.015662189066,
 10: 14313.402073168309,
 11: 14303.807710203326,
 12: 14294.232528543549,
 13: 14284.676488231582,
 14: 14275.139550589009,
 15: 14265.621677322402,
 16: 14256.122830294258,
 17: 14246.642971463887,
 18: 14237.182062871992,
 19: 14227.740066636548,
 20: 14218.31694495162,
 21: 14208.912660086957,
 22: 14199.527174387742,
 23: 14190.160450274438,
 24: 14180.812450242636,
 25: 14171.483136862902,
 26: 14162.172472780612,
 27: 14152.880420715823,
 28: 14143.606943463108,
 29: 14134.352003891425,
 30: 14125.115564943946,
 31: 14115.89758963792,
 32: 14106.698041064532,
 33: 14097.516882388742,
 34: 14088.354076849148,
 35: 14079.209587757821,
 36: 14070.083378500194,
 37: 14060.975412534872,
 38: 14051.885653393512,
 39: 14042.814064680677,
 40: 14033.76

__LogisticRegression:__
__1.__ Use the dataset breast-bin.csv 
__2.__ Divide the dataset into train and test sets 
__3.__ Train the model. Which score do you get? And the cost?

In [22]:
breast_bin = read_csv(r'C:\Users\bruna\PycharmProjects\SIB\datasets\breast_bin\breast-bin.csv', sep=",", label=True, features=True)

In [24]:
from sklearn.preprocessing import StandardScaler
breast_bin.X = StandardScaler().fit_transform(breast_bin.X)

In [25]:
# split dataset
train_dataset, test_dataset = train_test_split(breast_bin)
test_dataset.y

array([0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1.])

In [26]:
# ridge classifier
log_reg = LogisticRegression()
log_reg.fit(train_dataset)
predictions = log_reg.predict(test_dataset)
predictions

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [27]:
log_reg.score(test_dataset)

0.6330935251798561

In [28]:
log_reg.cost(test_dataset)

0.6755481133533929

In [29]:
log_reg.cost_history

{0: 0.6920647051520261,
 1: 0.6920396929035482,
 2: 0.6920135117819125,
 3: 0.6919873446729974,
 4: 0.6919611906454122,
 5: 0.6919350496933446,
 6: 0.6919089218102561,
 7: 0.6918828069896118,
 8: 0.69185670522488,
 9: 0.6918306165095321,
 10: 0.6918045408370429,
 11: 0.6917784782008898,
 12: 0.6917524285945533,
 13: 0.6917263920115176,
 14: 0.6917003684452694,
 15: 0.6916743578892984,
 16: 0.6916483603370982,
 17: 0.6916223757821645,
 18: 0.6915964042179966,
 19: 0.6915704456380971,
 20: 0.6915445000359711,
 21: 0.6915185674051273,
 22: 0.6914926477390771,
 23: 0.6914667410313353,
 24: 0.6914408472754192,
 25: 0.6914149664648503,
 26: 0.691389098593152,
 27: 0.6913632436538515,
 28: 0.6913374016404784,
 29: 0.6913115725465664,
 30: 0.6912857563656513,
 31: 0.6912599530912724,
 32: 0.6912341627169722,
 33: 0.6912083852362958,
 34: 0.6911826206427918,
 35: 0.6911568689300117,
 36: 0.6911311300915103,
 37: 0.6911054041208448,
 38: 0.6910796910115762,
 39: 0.6910539907572683,
 40: 0.691028