__Test the PCA class in a jupyter notebook using the iris.csv dataset (classificação).__

In [2]:
import numpy as np
import pandas as pd
from si.Data.dataset import Dataset
from si.decomposition.pca import PCA
from si.IO.CSV import read_csv

In [10]:
df_iris = read_csv(r'C:\Users\bruna\PycharmProjects\SIB\datasets\iris\iris.csv', sep=",", label=True)


In [9]:
selector = PCA(n_components=2)
selector.fit_transform(df_iris)
selector.components

array([[ 0.36158968, -0.08226889,  0.85657211,  0.35884393],
       [-0.65653988, -0.72971237,  0.1757674 ,  0.07470647]])

In [6]:
selector.explained_variance

array([4.22484077, 0.24224357])

In [7]:
selector.mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])